publishdir: docs
title: Î”Y ~ acanalis
baseurl: https://acanalis.github.io/

en:
  languageCode: "en-us"

module:
  imports: 
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy

params:
  date_format: 2006/02/01
  copyright_license: 
    enable: true
    sharealike: true
    allow_commercial: true
    allow_derivatives: true
    notice: "Except where otherwise noted, this website is licensed under {license}"
  
  
markup:
  defaultMarkdownHandler : goldmark
  goldmark:
    renderer:
      unsafe: true 
  highlight: 
    codeFences: false  
  tableOfContents:
    startLevel : 2
    endLevel : 3


# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
#  name : "Home"
#  url : "/"
#  weight : 10

menu: 
  main:
    - name : "About"
      url : "about"
      weight : 20
    - name : "Posts"
      url : "post"
      weight : 30
