publishdir: docs
title: ΔY - Cana's blog
baseurl: https://acanalis.github.io/

theme: PaperMod

enableEmoji: true
pygmentsUseClasses: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
    extensions:
      linkify: false
  highlight:
    noClasses: false
  tableOfContents:
    startLevel: 1
    ordered: true
    endLevel: 2

params:
  env: production
  ShowReadingTime: true
  assets:
    disableFingerprinting: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true

defaultContentLanguage: en
languages:
  en:
    languageCode: "en-us"
    contentDir: content/en
    menu:
      main:
        - name: Posts
          url: post
          weight: 20
        - name: About
          url: about
          weight: 30
    params:
      homeInfoParams:
        Title: ΔY - Cana's blog

  es:
    languageCode: "es-ar"
    contentDir: content/es
    menu:
      main:
        - name: Posts
          url: post
          weight: 20
        - name: Acerca de @acanalis
          url: about
          weight: 30
    params:
      homeInfoParams:
        Title: ΔY - Cana's blog