publishdir: docs
title: ΔY
baseurl: https://acanalis.github.io/

module:
  imports: 
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy

params:
  date_format: 2006/02/01
  main_menu:
    show_language: true
  
  
markup:
  defaultMarkdownHandler : goldmark
  goldmark:
    renderer:
      unsafe: true 
  highlight: 
    codeFences: false  
  tableOfContents:
    startLevel : 2
    endLevel : 3


defaultContentLanguage: en
languages: 
  en: 
    languageCode: "en-us"
    contentDir: content/en
    menu: 
      main:
        - name : "Posts"
          url : "post"
          weight : 20
        - name : "About @acanalis"
          url : "about"
          weight : 30
    params:
      copyright_license:
          enable: true
          sharealike: true
          allow_commercial: true
          allow_derivatives: true
          notice: "Except where otherwise noted, this website is licensed under {license}"

  es: 
    languageCode: "es-ar"
    contentDir: content/es
    menu:
      main:
        - name : "Posts"
          url : "post"
          weight : 20
        - name : "Acerca de @acanalis"
          url : "about"
          weight : 30
    params:
      copyright_license:
        enable: true
        sharealike: true
        allow_commercial: true
        allow_derivatives: true
        notice: "Excepto indicación en contrario, este sitio está licenciado bajo {license}"

       


